### ISSUE TITLE
construct a label from other benchmark fields

### ISSUE THREAD

**Issue by cwpearson** [rai-project/scope_plot#3]

**Comment by abduld** [comment]
![image](https://user-images.githubusercontent.com/1404191/44056520-8202d29a-9f16-11e8-8d6c-da8b4a62fe60.png)

e.g. from https://ml-arc-minsky.netlify.com/machine/AWS_g3_xlarge

**Comment by cwpearson** [comment]
Can you add a snippet of the benchmark.json file as well?

**Comment by abduld** [comment]
e.g. 

```
 {
      "name": "SGEMM/384/169/1",
      "iterations": 13074,
      "real_time": 5.3525743996501726e+04,
      "cpu_time": 5.3539960532357516e+04,
      "time_unit": "ns",
      "K": 1.0000000000000000e+00,
      "M": 3.8400000000000000e+02,
      "N": 1.6900000000000000e+02
    }, 
```

https://github.com/rai-project/scope/blob/master/results/raw_data/minsky/sgemm_smt_0.json

**Comment by cwpearson** [comment]
What about something like this. This would construct a string with the specified seperator, from the fields in each benchmark object

In the spec file
```yaml
label:
  seperator: "x" # optional, there would be some default
  fields:
  -  x
  -  k
  -  w
```

or on the command line

    ... --seperator x --fields x k w ...

**Comment by cwpearson** [comment]
Some more thoughts.
In the spec file, at the series level, `series.label` is the name of the series in the plot legend right now, so perhaps add another two optional fields `series.tick_fields` and `series.tick_seperator`
```yaml
series:
  - ...
    tick_seperator: "x" # optional, there would be some default
    tick_fields: [K, M, N]
  - ...
```

or for command line utilities

    ... --tick-seperator x --tick-fields K M N ...

The result for the offered snippet would be

    1x384x169

There will need to be some changes in how dataframes are generated in `scope_plot/benchmark.py` and consumed in the `generate_bar()` portions of `scope_plot/backends/...`.
I think when the dataframe is generated, the index of the dataframe should be set to the desired tick label.
Then, when that dataframe is consumed the logic would need to be adjusted a bit to plot it correctly.
