### ISSUE TITLE
travis: test on a stable python 3.7 environment

### ISSUE THREAD

**Issue by cwpearson** [rai-project/scope_plot#8]
Either try this in `.travis.yml`

```yaml
  python: 3.7
  dist: xenial
  sudo: true
```

or switch to using pyenv on both linux and macOS
